[package]
name = "surrealdb-node"
publish = false
edition = "2021"
version = "0.0.0"
authors = ["Tobie Morgan Hitchcock <tobie@surrealdb.com>"]
description = "Nodejs, Bun, and Deno driver for SurrealDB"
repository = "https://github.com/surrealdb/surrealdb.js"
license = "Apache License 2.0"

[profile.release]
lto = true
strip = true
opt-level = 'z'
panic = 'abort'
codegen-units = 1

[lib]
path = "src-rust/lib.rs"
crate-type = ["cdylib"]

[features]
kv-rocksdb = ["surrealdb-core/kv-rocksdb"]
kv-surrealkv = ["surrealdb-core/kv-surrealkv"]
kv-mem = ["surrealdb-core/kv-mem"]

[dependencies]
surrealdb-core = { path = "../../../surrealdb/surrealdb/core", default-features = false, features = [
    "http",
] }
surrealdb-types = { path = "../../../surrealdb/surrealdb/types", default-features = false }
napi = { version = "3", features = ["async", "serde-json"] }
napi-derive = "3"
serde = "1.0.197"
serde_json = "1.0.115"
channel = { version = "2.3.1", package = "async-channel" }
uuid = "1.8.0"
dashmap = "6.1.0"
anyhow = "1.0.101"

[build-dependencies]
napi-build = "2.2.3"
cargo-lock = "10.0.1"
